#!/bin/bash

# Check if subnet argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <subnet>"
    exit 1
fi

# Subnet to scan
SUBNET="$1"

echo "Checking LDAP signing enforcement on subnet $SUBNET..."

# Loop over each IP in the subnet generated by prips
for ip in $(prips "$SUBNET"); do
    echo "Checking $ip..."

    # Attempt an unsigned LDAP bind using ldapsearch
    ldapsearch -x -H ldap://$ip -b "" -s base "(objectclass=*)" -o ldif-wrap=no > /dev/null 2>&1

    # Check if LDAP signing is not enforced (successful connection without signing)
    if [ $? -eq 0 ]; then
        echo "$ip: LDAP signing NOT enforced"
    else
        echo "$ip: LDAP signing enforced or No response"
    fi
done

echo "LDAP signing check completed for subnet $SUBNET."
